/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,ts,svelte}"],
  theme: {
    extend: {
      colors: {
        "jnt-bg-primary": "var(--jnt-bg-primary)",
        "jnt-bg-secondary": "var(--jnt-bg-secondary)",
        "jnt-bg-tertiary": "var(--jnt-bg-tertiary)",
        "jnt-bg-elevated": "var(--jnt-bg-elevated)",
        "jnt-text-primary": "var(--jnt-text-primary)",
        "jnt-text-secondary": "var(--jnt-text-secondary)",
        "jnt-text-tertiary": "var(--jnt-text-tertiary)",
        "jnt-text-placeholder": "var(--jnt-text-placeholder)",
        "jnt-brand-50": "var(--jnt-brand-50)",
        "jnt-brand-100": "var(--jnt-brand-100)",
        "jnt-brand-200": "var(--jnt-brand-200)",
        "jnt-brand-300": "var(--jnt-brand-300)",
        "jnt-brand-400": "var(--jnt-brand-400)",
        "jnt-brand-primary": "var(--jnt-brand-primary)",
        "jnt-brand-hover": "var(--jnt-brand-hover)",
        "jnt-brand-active": "var(--jnt-brand-active)",
        "jnt-success": "var(--jnt-color-success)",
        "jnt-warning": "var(--jnt-color-warning)",
        "jnt-error": "var(--jnt-color-error)",
        "jnt-info": "var(--jnt-color-info)",
      },
      fontFamily: {
        "jnt-sans": "var(--jnt-font-sans)",
        "jnt-mono": "var(--jnt-font-mono)",
      },
      fontSize: {
        "jnt-xs": "var(--jnt-text-xs)",
        "jnt-sm": "var(--jnt-text-sm)",
        "jnt-base": "var(--jnt-text-base)",
        "jnt-lg": "var(--jnt-text-lg)",
        "jnt-xl": "var(--jnt-text-xl)",
        "jnt-2xl": "var(--jnt-text-2xl)",
        "jnt-3xl": "var(--jnt-text-3xl)",
      },
      spacing: {
        "jnt-1": "var(--jnt-space-1)",
        "jnt-2": "var(--jnt-space-2)",
        "jnt-3": "var(--jnt-space-3)",
        "jnt-4": "var(--jnt-space-4)",
        "jnt-5": "var(--jnt-space-5)",
        "jnt-6": "var(--jnt-space-6)",
        "jnt-8": "var(--jnt-space-8)",
        "jnt-10": "var(--jnt-space-10)",
        "jnt-12": "var(--jnt-space-12)",
      },
      borderRadius: {
        "jnt-sm": "var(--jnt-radius-sm)",
        "jnt-md": "var(--jnt-radius-md)",
        "jnt-lg": "var(--jnt-radius-lg)",
        "jnt-xl": "var(--jnt-radius-xl)",
        "jnt-full": "var(--jnt-radius-full)",
      },
      boxShadow: {
        "jnt-sm": "var(--jnt-shadow-sm)",
        "jnt-md": "var(--jnt-shadow-md)",
        "jnt-lg": "var(--jnt-shadow-lg)",
        "jnt-xl": "var(--jnt-shadow-xl)",
      },
      transitionDuration: {
        "jnt-fast": "var(--jnt-duration-fast)",
        "jnt-normal": "var(--jnt-duration-normal)",
        "jnt-slow": "var(--jnt-duration-slow)",
      },
      transitionTimingFunction: {
        "jnt-standard": "var(--jnt-ease-standard)",
        "jnt-in": "var(--jnt-ease-in)",
        "jnt-out": "var(--jnt-ease-out)",
      },
    },
  },
  plugins: [],
};
